# Charles DeGennaro

### 1: Convert the RGB to HSV code so it produces values in OpenCv's specified ranges and array structure. Your function should accept a 3D array and return HSV values in OpenCv's ranges. H -> [0,180], S -> [0,255], V -> [0,255]

#### To test your function use the following rgb value: rgb = np.uint8([[[200,74,55]]])

#### Your function should return: [[[4, 185, 200]]]

In [137]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [138]:
def rgb_to_hsv_single(rgb):
    # Input: rgb is a 1-D array with values in range [0..255]
    # r = rgb[0], g = rgb[1], b = rgb[2]
    # Output: hsv is a 1-D array with values in range h = [0..255], s = [0..1], v = [0..1]
    
    # Normalize input
    rgb = rgb/255
    
    h = 0.0
    s = 0.0
    v = 0.0
    
    # Find the max and min RGB values
    v = np.max(rgb)
    vMin = np.min(rgb)
    
    diff = v-vMin
    
    if v == 0:
        s = 0
    else:
        s = diff/v
        
        
    if rgb[0] == rgb[1] and rgb[1] == rgb[2]:
        h = 0
    elif v == rgb[0]:
        h = 60*(rgb[1]-rgb[2])/diff
    elif v == rgb[1]:
        h = 120*(rgb[2]-rgb[0])/diff
    elif v == rgb[2]:
        h = 240*(rgb[0]-rgb[1])/diff
        
    return np.array([h,s,v])

In [139]:
def rgb_to_hsv(rgb):
    # Input: rgb is a 3-D array with values in range [0..255]
    # 2 Dimensions are for pixel coordinates
    # 1 Dimension is for the RGB values
    # The deepest layer is the RGB information
    
    hsv = np.zeros((rgb.shape[0], rgb.shape[1], rgb.shape[2]), dtype=np.double)
    
    for i in range(len(rgb)):
        for j in range(len(rgb[i])):
            hsv[i][j] = rgb_to_hsv_single(rgb[i][j])
    
    return hsv    

In [140]:
def hsv_to_opencv(hsv):
    new_hsv = np.zeros((hsv.shape[0], hsv.shape[1], hsv.shape[2]), dtype=np.uint8)
    for i in range(len(hsv)):
        for j in range(len(hsv[i])):
            s = np.interp(hsv[i][j][1],[0,1],[0,255])
            v = np.interp(hsv[i][j][2],[0,1],[0,255])
            new_hsv[i][j] = [round(hsv[i][j][0]/2),round(s),round(v)]
    return new_hsv

In [141]:
# rgb = np.uint8([[[200,74,55],[170,123,23]], [[170,123,23],[200,74,55]]])
rgb = np.uint8([[[200,74,55]]])

print('rgb:\n', rgb)
hsv = rgb_to_hsv(rgb)
print('hsv:\n', hsv)
new_hsv = hsv_to_opencv(hsv)
print('converted hsv:\n', new_hsv)


rgb:
 [[[200  74  55]]]
hsv:
 [[[7.86206897 0.725      0.78431373]]]
converted hsv:
 [[[  4 185 200]]]


### 2. Extra credit: Write the Python code for the conversion of HSV color space to RGB. The algorithm is below. The code is available online but please write it on your own. Include comments to describe each step in your code.

In [142]:
def hsv_to_rgb_single(hsv):
    # Input: 1d np array where:
    # hsv[0] = H [0..360]
    # hsv[1] = S [0..1]
    # hsv[2] = V [0..1]
    
    H = hsv[0]
    S = hsv[1]
    V = hsv[2]
    
    C = V * S
    X = C * (1 - abs((H / 60) % 2 - 1))
    m = V - C
    
    # Rp, Gp, and Bp are the R', G', and B' from the table online
    Rp, Gp, Bp = hsv_to_rgb_intermediary_step(H,C,X)
    
    R = (Rp + m) * 255
    G = (Gp + m) * 255
    B = (Bp + m) * 255
    
    return np.uint8([R, G, B])
    
    
def hsv_to_rgb_intermediary_step(H,C,X):
    # Return the R', G', and B' values
    if H < 60:
        return C, X, 0
    if H < 120:
        return X, C, 0
    if H < 180:
        return 0, C, X
    if H < 240:
        return 0, X, C
    if H < 300:
        return X, 0, C
    return C, 0, X

In [143]:
def hsv_to_rgb(hsv):
    # Input: rgb is a 3-D array with values in range [0..255]
    # 2 Dimensions are for pixel coordinates
    # 1 Dimension is for the RGB values
    # The deepest layer is the RGB information
    
    rgb = np.zeros((hsv.shape[0], hsv.shape[1], hsv.shape[2]), dtype=np.uint8)
    
    for i in range(len(hsv)):
        for j in range(len(hsv[i])):
            rgb[i][j] = hsv_to_rgb_single(hsv[i][j])
    
    return rgb    

In [144]:
print('rgb:\n', rgb)
print('hsv:\n', hsv)
hsv_2_rgb = hsv_to_rgb(hsv)
print('hsv_2_rgb:\n', hsv_2_rgb)

rgb:
 [[[200  74  55]]]
hsv:
 [[[7.86206897 0.725      0.78431373]]]
hsv_2_rgb:
 [[[200  74  55]]]
