### Differences between Python and NumPy

Python, by default, offers a list object that can be used to represent arrays. For more advanced operations, especially for numerical tasks like matrix operations, NumPy, a third-party library, provides a more efficient and feature-rich array object.

In this notebook, we'll explore the differences between standard Python and NumPy in terms of math and matrix operations.


In [18]:
# They both used Brackets []

# Python List
list = [1,2,3]
print("Python list:", list)

# Numpy array
import numpy as np
arr = np.array([1,2,3])
print("NumPy array:", arr)

Python list: [1, 2, 3]
NumPy array: [1 2 3]


In [23]:
# Both can access the elements with an index. 

# Python List
print("Python list:",list[0])

# Numpy Array
print("Numpy Array:",arr[0])

# And slice/filter out elements

# Python List
print("Python list:",list[:2])

# Numpy Array
print("Numpy Array:",arr[:2])

Python list: 1
Numpy Array: 1
Python list: [1, 2]
Numpy Array: [1 2]


In [24]:
# Python lists don't support mathematical operations

list = list*2
print("Python list:", list)

# Multiplication repeats the array elements

Python list: [1, 2, 3, 1, 2, 3]


In [25]:
# NumPy array's support mathematical operations.  Very important for us!

arr = arr*2
print("NumPy array:",arr)

NumPy array: [2 4 6]


In [27]:
# NumPy array's can set the data types.   Very import for us!
arr = np.array([1,2,3], np.uint8)
print(arr.dtype)

uint8


In [29]:
# Create an empty array. Return a new array of given shape and type, without initializing entries.

# Create an empty array
arr = np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
# Create an 2D array of zeros
arr = np.zeros((2,3))
print("Zeros:\n",arr)

# Create an 2D array of ones
arr = np.ones((2,3))
print("Ones:\n",arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [39]:
# Array with a range of values
range_array = np.arange(0, 10, 2)
print("Range Array:\n", range_array)

# Array of evenly spaced values over a specified range
linspace_array = np.linspace(0, 1, 5)
print("Linear Space Array:\n", linspace_array)


Range Array:
 [0 2 4 6 8]
Linear Space Array:
 [0.   0.25 0.5  0.75 1.  ]


In [42]:
# Statistical Functions

# Sum
sum_val = np.sum(np.array([1,2,3,4]))
print("Sum:", sum_val)

# Mean
mean_val = np.mean(np.array([1,2,3,4]))
print("\nMean:", mean_val)


Sum: 10

Mean: 2.5


### Matrices

In [21]:

import numpy as np

# Create two 2x2 matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [0, 2]])

print("A:\n",A)

print("B:\n",B)

A:
 [[1 2]
 [3 4]]
B:
 [[2 0]
 [0 2]]


In [11]:
# Addition
C = A + B
print("Addition:\n", C)

# Subtraction
D = A - B
print("\nSubtraction:\n", D)


Addition:
 [[3 2]
 [3 6]]

Subtraction:
 [[-1  2]
 [ 3  2]]


In [22]:
print("A:\n",A)

print("B:\n",B)

# Multiplication
E = np.dot(A, B)
print("\nMultiplication:\n", E)


A:
 [[1 2]
 [3 4]]
B:
 [[2 0]
 [0 2]]

Multiplication:
 [[2 4]
 [6 8]]


In [33]:
print("A:\n",A)

print("B:\n",B)

# Element-wise multiplication
F = A * B
print("\nElement-wise multiplication:\n", F)



A:
 [[1 2]
 [3 4]]
B:
 [[2 0]
 [0 2]]

Element-wise multiplication:
 [[2 0]
 [0 8]]


In [35]:
print("A:\n",A)

# Transpose
G = A.T
print("\nTranspose of A:\n", G)

A:
 [[1 2]
 [3 4]]

Transpose of A:
 [[1 3]
 [2 4]]
