In [5]:
import cv2
import numpy as np
from numpy import interp

def rgb_to_hsv(rgb):
    rgb = rgb/255

    h = 0.0
    s = 0.0
    v = 0.0

    v = np.max(rgb)
    vMin = np.min(rgb)

    if(v>0.0):
        s = (v - vMin)/v
    else:
        s = 0.0
    
    diff = (v-vMin)
    
    if(rgb[0,0,0] == rgb[0,0,1] and rgb[0,0,1] == rgb[0,0,2]):
        h = 0
    elif(rgb[0,0,0] == v):
        h = 60 *(rgb[0,0,1] - rgb[0,0,2])/diff
    elif(rgb[0,0,1] == v):
        h = 120 + 60 * (rgb[0,0,2] - rgb[0,0,0]) / diff
    elif(rgb[0,0,2] == v):
        h = 240 + 60 * (rgb[0,0,0] -rgb[0,0,1])/ diff
    

    return np.array([[[h,s,v]]])



rgb = np.array([[[200, 74, 55]]])

hsv = rgb_to_hsv(rgb)

print(rgb)
print(hsv)

rgb_cv = np.uint8([[[200,74,55]]])
hsv_cv = cv2.cvtColor(rgb_cv, cv2.COLOR_RGB2HSV)
print(hsv_cv)

[[[200  74  55]]]
[[[7.86206897 0.725      0.78431373]]]
[[[  4 185 200]]]
