In [24]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import math

In [33]:
def rgbtohsv(rgb):
    #takes in your 3-d array returns list of hsv values
    hsv = []
    #declare hsv list
    #iterate through the 3d array to get individual rgb values
    for x in rgb:
        for y in x:
            for z in y:
                z = z/255.0
                #divide each value in a [r,g,b] by 255
            
            r = y[0]
            g = y[1]
            b = y[2]
            #call helper function and append to hsv array
            hsv.append(helper(r, g, b))
    return hsv
def helper(r, g, b):
    #get max and min values
    maxc = max(r, g, b)
    minc = min(r, g, b)
    v = maxc
    if minc == maxc:
        return 0.0, 0.0, v
    s = (maxc-minc) / maxc
    rc = (maxc-r) / (maxc-minc)
    gc = (maxc-g) / (maxc-minc)
    bc = (maxc-b) / (maxc-minc)
    if r == maxc:
        h = 0.0+bc-gc
    elif g == maxc:
        h = 2.0+rc-bc
    else:
        h = 4.0+gc-rc
    h = (h/6.0) % 1.0
    return [h * 360, s * 100, v ]


rgb = np.uint8([[[200,74,55]]])
print(rgbtohsv(rgb))
#not sure why this is not returning the correct values I found this algorithm online and it was consistent with every other one i found





x
[[200  74  55]]
y
[200  74  55]
x
[[200  74  55]]
y
[200  74  55]
[[7.862068965517244, 72.5, 20000], [7.862068965517244, 72.5, 20000]]
