# Project 1 - Part 1

### Hyesoo Choi (Heh-soo Choi)

### <b>Project 1 - part 1 </b>

**(1)** Convert the RGB to HSV code so it produces values in OpenCv's specified ranges and array structure.  Your function should accept a 3D array and return HSV values in OpenCv's ranges. H -> [0,180], S -> [0,255], V -> [0,255]<p> To test your function use the following rgb value: <code>rgb = np.uint8([[[200,74,55]]])</code> <br>  Your function should return: [[[4, 185, 200]]]<p>
**(2)**  Write the Python code for the conversion of HSV color space to RGB.  The algorithm is below.  The code is available online but please write it on your own.  Include comments to describe each step in your code. <p>


In [195]:
# 1) rgb -> hsv in openCV's range (_version1 that handles all ranges of rgb)
# Note: I used the formula from this website https://www.rapidtables.com/convert/color/rgb-to-hsv.html
#       because when I tried different values of rgb, it sometimes gave me the negative values with the given formula from our class.
#       If that negative value is added to 360, the hsv value is correct, but the code was not handling this correctly.
#       so I tried this formula instead, and it handles all values of rgb
#       I have a different version of this code with the given formula from our class at the bottom of this note. 
  
import numpy as np

def rgb_to_hsv_cv(rgb):
  # input: rgb 3D array with values in range [0,255]
  # r = rgb[0,0,0], g = rgb[0,0,1], b = rgb[0,0,2]
  # [[[r,g,b]]]
  # output: hsv values in a 3D array in openCV's ranges h = [0-180], s = [0-255], v = [0-255]

  # Normalize values between 0-1
  rgb = rgb/255

  # Initialize HSV
  h = 0.0
  s = 0.0
  v = 0.0

  # Vmax & Vmin
  v = np.max(rgb)

  vMin = np.min(rgb)

  # Set the saturation value
  if(v == 0):
    s = 0.0
  else:
    s = (v - vMin)/v

  # Difference from vMax to vMin
  diff = v - vMin
  
  # set variables
  r = rgb[0,0,0]
  g = rgb[0,0,1]
  b = rgb[0,0,2]

  # Are r,g,b equal?
  if (r == g and g == b and r == b):
    h = 0
  
  # Is the hue point within +/- 60 degrees of the red axis
  if(r == v):
    h = 60 * ((g - b) / diff % 6)

  # Is the hue point within +/- 60 degrees of the green axis
  if(g == v):
    h = 60 * ((b - r) / diff + 2)

  # Is the hue point within +/- 60 degrees of the blue axis
  if(b == v):
    h = 60 * ((r- g) / diff + 4)

  # hsv 3D array
  hsv = np.array([[[h,s,v]]])
  
  # convert to openCv range
  s = np.interp(hsv[0,0,1], [0,1], [0,255])
  v = np.interp(hsv[0,0,2], [0,1], [0,255])

  # round it to integer, and divide hue value by 2 for openCV range (0-180)
  hsv_cv = np.array([[[round(hsv[0,0,0]/2), round(s), round(v)]]])
  
  return hsv_cv

#  create an rgb 3d array
rgb = np.array([[[200,74,55]]])

# send rgb array to rgb_to_hsv_cv
hsv = rgb_to_hsv_cv(rgb)


print("The original RGB value: \n", rgb)
print("Converted to HSV openCV value: \n", hsv)


The original RGB value: 
 [[[200  74  55]]]
Converted to HSV openCV value: 
 [[[  4 185 200]]]


In [196]:
# 2) hsv (open cv range) -> rgb
# 0 <= h < 360, 0 <= s <= 1, 0 <= v <= 1
# h = hsv[0,0,0] s = hsv[0,0,1] v = hsv[0,0,2]
# Input: 3D hsv openCV range array
# output: return rgb 3D array
import numpy as np

def hsv_to_rgb(hsv):

  # set variables for h,s,v
  # calculate hsv within the appropriate range 
  # h * 2 because openCv used 1/2 value of h
  h = hsv[0,0,0] * 2 
  s = hsv[0,0,1] / 255
  v = hsv[0,0,2] / 255

  # formula
  c = v * s
  x = c * (1 - abs((h/60) % 2 - 1))
  m = v - c

  # Get r'g'b' values according to h value (from the given formula)
  if(0 <= h and h < 60):
    rgb_temp = np.array([[[c,x,0]]])
  elif(60 <= h and h < 120):
    rgb_temp = np.array([[[x,c,0]]])
  elif(120 <= h and h < 180):
    rgb_temp = np.array([[[0,c,x]]])
  elif(180 <= h and h < 240):
    rgb_temp = np.array([[[0,x,c]]])    
  elif(240 <= h and h < 300):
    rgb_temp = np.array([[[x,0,c]]])
  elif(300 <= h and h < 360):
    rgb_temp = np.array([[[c,0,x]]])        

  # get rgb values based on the results of calculation above
  rgb = np.array([[[round((rgb_temp[0,0,0] + m) * 255) , round((rgb_temp[0,0,1] + m) * 255), round((rgb_temp[0,0,2] + m) * 255) ]]])

  return rgb

# pass the hsv with openCV value to convert to rgb
rgb = hsv_to_rgb(hsv)
print("hsv input (openCV range): \n", hsv)
print("rgb returned: \n", rgb)


hsv input (openCV range): 
 [[[  4 185 200]]]
rgb returned: 
 [[[200  74  55]]]


 ---
Checking and Extra

In [197]:
# 1) rgb -> hsv in openCV's range (version2 with formula we used in class (reference))
# Note: This code uses the given formula from our class.

import numpy as np

def rgb_to_hsv_cv(rgb):
  # input: rgb 3D array with values in range [0,255]
  # r = rgb[0,0,0], g = rgb[0,0,1], b = rgb[0,0,2]
  # [[[r,g,b]]]
  # output: hsv values in a 3D array in openCV's ranges h = [0-180], s = [0-255], v = [0-255]

  # Normalize values between 0-1
  rgb = rgb/255

  # Initialize HSV
  h = 0.0
  s = 0.0
  v = 0.0

  # Vmax & Vmin
  v = np.max(rgb)

  vMin = np.min(rgb)

  # Set the saturation value
  if(v == 0):
    s = 0.0
  else:
    s = (v - vMin)/v

  # Difference from vMax to vMin
  diff = v - vMin
  
  # set variables
  r = rgb[0,0,0]
  g = rgb[0,0,1]
  b = rgb[0,0,2]

  # Are r,g,b equal?
  if (r == g and g == b and r == b):
    h = 0
  
  # Is the hue point within +/- 60 degrees of the red axis
  if(r == v):
    h = 60 * (g - b) / diff

  # Is the hue point within +/- 60 degrees of the green axis
  if(g == v):
    h =  120 + 60 * (b - r) / diff

  # Is the hue point within +/- 60 degrees of the blue axis
  if(b == v):
    h = 240 + 60 * (r - g) / diff  

  # hsv 3D array
  hsv = np.array([[[h,s,v]]])
  
  # convert to openCv range
  s = np.interp(hsv[0,0,1], [0,1], [0,255])
  v = np.interp(hsv[0,0,2], [0,1], [0,255])

  # round it to integer, and divide hue value by 2 for openCV range (0-180)
  hsv_cv = np.array([[[round(hsv[0,0,0]/2), round(s), round(v)]]])
  
  return hsv_cv

#  create an rgb 3d array
rgb = np.array([[[200,74,55]]])

# send rgb array to rgb_to_hsv_cv
hsv = rgb_to_hsv_cv(rgb)


print("The original RGB value: \n", rgb)
print("Converted to HSV openCV value: \n", hsv)


The original RGB value: 
 [[[200  74  55]]]
Converted to HSV openCV value: 
 [[[  4 185 200]]]


In [198]:
# Checking HSV value with openCV function
import cv2
import numpy as np

rgb = np.uint8( [[[200,74,55]]])
hsv = cv2.cvtColor(rgb, cv2.COLOR_RGB2HSV)

print(hsv)

[[[  4 185 200]]]
