In [28]:
import numpy as np

arr_2D = np.array([[50,75,100], [125,150,175], [200,225,250]])

print("Original Array:\n",arr_2D)

# Correct slicing format for desired output. 
# Both slices happening at the same time. 
# This will give you the desired output

print("\nCorrect Slicing Format")
print("\nC:\n", arr_2D[:,:2])
print("\nD:\n", arr_2D[1:,:2])


Original Array:
 [[ 50  75 100]
 [125 150 175]
 [200 225 250]]

Correct Slicing Format

C:
 [[ 50  75]
 [125 150]
 [200 225]]

D:
 [[125 150]
 [200 225]]
