### Module 1 Answers

***

In [13]:
# Import Libraries
import numpy as np

#(1) 50,75,100,125,150,175,200,225.  Show this sequence of values in a 1D and 2D array.
arr_1D = np.array([50,75,100,125,150,175,200,225])
print("1D array: ", arr_1D)
arr_2D = np.array([[50,75,100,125],[150,175,200,225]])
print("2D array: ", arr_2D)

#(2) 50,75,100,125,150,175,200,225,250.  In a 1D array, what is the array position of the value 150?<br><br> 
arr_1D = np.array([50,75,100,125,150,175,200,225,250])
print("The array position of 150 in arr_1D is: ",np.where(arr_1D == 150), "with the value of: ",arr_1D[4])

#(3) 50,75,100,125,150,175,200,225,250.  In a 3x3 2D array, what is the array position of the value 150?<br><br> 
arr_2D = np.array([[50,75,100],[125,150,175],[200,225,250]])
print("The array position of 150 in arr_2D is: ",np.where(arr_2D == 150), "with the value of: ",arr_2D[1][1])
print("The shape of arr_2D is: ",arr_2D.shape)
#(4) Find a photo from Google Images, save it as a variable, and draw it using matplotlib.<br><br> 


1D array:  [ 50  75 100 125 150 175 200 225]
2D array:  [[ 50  75 100 125]
 [150 175 200 225]]
The array position of 150 in arr_1D is:  (array([4]),) with the value of:  150
The array position of 150 in arr_2D is:  (array([1]), array([1])) with the value of:  150
The shape of arr_2D is:  (3, 3)


In [33]:
'''
(A)
[100,175,250]

(B)
[125, 150, 175]

(C)
[[50,75]
[125,150]
[200,225]]

(D)
[[125 150]
[200 225]]
'''

import numpy as np

# Original 3x3 array
arr_2d = np.array([[50, 75, 100],
                   [125, 150, 175],
                   [200, 225, 250]])

# Answer: (A) [100,175,250]
subbarray = arr_2d[:,2:]
print("A:\n", subbarray)

#(B)[125, 150, 175]
subbarray = arr_2d[1:2,:]
print("B:\n", subbarray)

#(C)
#[[50,75]
#[125,150]
#[200,225]]\
subbarray = arr_2d[:,:2]
print("C:\n", subbarray)

#(D)
#[[125 150]
#[200 225]]
subbarray = arr_2d[1:3,:2]
print("D:\n", subbarray)



A:
 [[100]
 [175]
 [250]]
B:
 [[125 150 175]]
C:
 [[ 50  75]
 [125 150]
 [200 225]]
D:
 [[125 150]
 [200 225]]


In [40]:
#(6)  Create a 2-D and 3-D array with Integers 0-47. 

arr_2D = np.arange(48).reshape(8,6)
print("2D array:\n", arr_2D)
print("arr_2D's shape is: ",arr_2D.shape)

arr_3D = np.arange(48).reshape(4,4,3)
print("3D array:\n", arr_3D)
print("arr_3D's shape is: ",arr_3D.shape)

2D array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]
arr_2D's shape is:  (8, 6)
3D array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
arr_3D's shape is:  (4, 4, 3)
