# Review of Python, Lists, & NumPy

"A complex system that works is invariably found to have evolved from a simple system that worked" &ndash; John Gall
<hr>

### Python

Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.
<p>
Python is dynamically typed and garbage collected. 
<p>
The progression from assembly language to C to Python represents a move up the abstraction ladder in the world of programming languages. Each step abstracts away some of the lower-level details, making it easier to write complex software.
<p>

The language stack:
<b>Assembly language -> C -> Python</b><p>


In [9]:
# Define a variable
a = 1
print(a)

1


In [7]:
# Dynamically typed variables
print(type(a))

<class 'str'>


In [10]:
# Control Statements
if a == 1:
    print("a is equal to 1")

a is equal to 1


In [12]:
def my_function(a):
    print("what is the value of a:", a)
    return a + 1

returned_value = my_function(1)
print(returned_value)

what is the value of a: 1
2


### Differences between Python Lists and NumPy Arrays

Python, by default, offers a list object that can be used to represent arrays. For more advanced operations, especially for numerical tasks like matrix operations, NumPy, a third-party library, provides a more efficient and feature-rich array object.

NumPy is based on two fundamental objects: an N-dimensional array object (ndarray) and a universal function object (ufunc).  An N-dimensional array is a homogeneous collection of "items" indexed by N integers.  There two essential pieces of metadata that define an N-dimensional array: 1) the shape of the array, and 2) the kind of items that composes the array. 

In this notebook, we'll explore the differences between standard Python and NumPy in terms of math and matrix operations.


In [13]:
# Python List
list = [1,2,3]
print('Python List:', list)

Python List: [1, 2, 3]


In [22]:
# NumPy array
import numpy as np

arr = np.array([1,2,3])
print("NumPy array:", arr)

NumPy array: [1 2 3]


In [18]:
# Python List
print("Python list first element:", list[0])

# NumPy array
print("NumPy array first element:", arr[0])

Python list first element: 1
NumPy array first element: 3


In [19]:
# Python list math

list = list * 2
print("Python list:", list)

Python list: [1, 2, 3, 1, 2, 3]


In [23]:
# NumPy list multiplication

arr = arr * 2
print("NumPy array:", arr)

NumPy array: [2 4 6]


In [25]:
arr = np.array([1,2,3], np.uint8)
print(arr.dtype)

float16


In [26]:
empty_array = np.empty((3,3))
print(empty_array)

[[ 2.60605835e-31 -5.21211670e-31  1.30302917e-31]
 [-5.21211670e-31  1.13363538e-30 -3.51817877e-31]
 [ 1.30302917e-31 -3.51817877e-31  2.01969522e-31]]


In [27]:
zero_array = np.zeros((2,3))
print("Zeros:\n", zero_array)

Zeros:
: [[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
range_array = np.arange(0,10,2)
print('Range array:\n', range_array)

Range array:
 [0 2 4 6 8]


Both are zero-indexed, meaning that the first element in the array is 0, the second is 1...<p>

Slicing allows us to extract a portion of the array.  It's done using the ":" or "..." symbols.  The basic syntax is start:stop:step<p>

<ul>
<li>start is the index where slicing starts(inclusive)</li>
<li>stop is the index where slicing stops(exclusive)</li>
<li>step specifies the interval between elements.</li>
</ul>

For example, `array[2:5]` would give you elements from index 2 to 4.  `array[::2]` would give you every second element.


In [30]:
array = np.arange(60)
print("1D array:\n", array)

1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [31]:
reshaped_array = array.reshape(3,4,5)
print("3D array:\n", reshaped_array)

3D array:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [34]:
print(reshaped_array[2,:,:])

[[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


### Matrices

In [36]:
A = np.array([[1,2], [3,4]])
B = np.array([[2,0], [0,2]])

print("A:\n", A)
print("B:\n", B)

A:
 [[1 2]
 [3 4]]
B:
 [[2 0]
 [0 2]]


In [37]:
C = A + B
print(C)

[[3 2]
 [3 6]]


In [38]:
D = A - B
print(D)

[[-1  2]
 [ 3  2]]


In [39]:
E = A * B
print(E)

[[2 0]
 [0 8]]
